name: CI-CD

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
  
    steps:
     - uses: actions/checkout@v2
 
     - name: Docker Login
       uses: docker/login-action@v1.14.1
       with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}
          
     - name: Build and push Docker images
       uses: docker/build-push-action@v2
       with:
         context: /home/israel/rotten-potatoes/src/
         file: /home/israel/rotten-potatoes/src/dockfile
         push: true
         tags: |  
           barrosneto/rooten-potatoes:latest 
           barrosneto/rooten-potatoes: ${{} github.run_number }} 

  CD:
    runs-on: ubuntu-latest
      
    steps: 
     - uses: actions/checkout@v2
     
     - name: Kubernetes Set Context
       uses: Azure/k8s-set-context@v2
       with:
         method: kubeconfig
         kubeconfig: ${{ secrets.k8s_KUBECONFIG }}
   
