

name: CI-CD


on:

  push:
    branches: [ main ]

 
  workflow_dispatch:


jobs:
  
  build:
 
    runs-on: ubuntu-latest

  
    steps:
    
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: /home/israel/rotten-potatoes/k8s
          file: /home/israel/rotten-potatoes/k8s
          push: true
          tags: |  
            barrosneto/rooten-potatoes:latest 
            barrosneto/rooten-potatoes:latest 
       
   
